// /*
//  * This Kotlin source file was generated by the Gradle 'init' task.
//  */
package trial.kotlin.cmddemo

import kotlinx.coroutines.*
import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.http.*

suspend fun main() = coroutineScope {
    launch { 
        delay(1000)
        println("Kotlin Coroutines World!") 
        try {
            val client = HttpClient()
            val r = client.post("http://127.0.0.1:12345/log?id=4444") {
                contentType(ContentType.Text.Plain)
                setBody("content123456789")
            }
            println(r.status.value)
            println(r.status.description)
        } catch (e: Exception) {
            println(e)
        }
    }
    println("Hello")
}
